  0%|             /home/austin/miniconda3/envs/sedd/lib/python3.9/site-packages/lightning/pytorch/core/module.py:441: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
Batch: 143. Train loss: 1.8195027479271357: : 144it [00:30,  4.75it/s]
  0%|                                                                                                                              | 0/1 [00:30<?, ?it/s]
Traceback (most recent call last):
  File "/home/austin/sdpo-private/sdpo_dna/finetune_sdpo.py", line 94, in <module>
    total_loss += loss.item()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/austin/sdpo-private/sdpo_dna/finetune_sdpo.py", line 94, in <module>
    total_loss += loss.item()
KeyboardInterrupt
